version: '3.8'
services:
  app:
    image: go-bookstore
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
#    networks:
#      - matt-net
    ports:
      - 8080:8080
    depends_on:
      - mysql-db

  mysql-db:
    platform: linux/amd64
    image: mysql:5.7
#    networks:
#      - matt-net
    environment:
      - MYSQL_ROOT_HOST=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=matthew
      - MYSQL_PASSWORD=password1234
      - MYSQL_DATABASE=bookstore-db
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
#
#networks:
#  matt-net:
#    driver: bridge

