version: '3.8'
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - mattnet
    ports:
      - 8080:8080
    depends_on:
      - mysql-db

  mysql-db:
    platform: linux/amd64
    image: mysql:8.0.22
    container_name: go-bookstoreDB
    networks:
      - mattnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_database
      MYSQL_USER: go_test
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306

networks:
  mattnet:
    driver: bridge

