version: '3.8'

services:
  app:
    build:
      context: .
    image: go-bookstore
    # profiles: [test, instant]
    volumes:
      - .:/app
    # env_file:
    #   - .envs/.env.local
    depends_on:
       - mysql
  
  mysql:
    image: mysql:5.7.33
    # m1 mac 일 경우 아래 platform은 주석
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test